import { defineConfig, type Plugin } from "vite";

// Hand-written service worker with a build-time precache manifest. A small
// plugin collects every emitted (hashed) file plus the public app-shell assets,
// injects them and a content-derived version into the SW template, and emits
// sw.js at the site root. The SW precaches the shell on install, serves assets
// cache-first with a background update, and drops old version caches on
// activate so a new build never strands users on stale files.

const PUBLIC_SHELL = [
  "/",
  "/index.html",
  "/manifest.webmanifest",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/icon-192-maskable.png",
  "/icons/icon-512-maskable.png",
];

function hashList(s: string): string {
  // FNV-1a 32-bit, hex; changes whenever the precache set changes.
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(16);
}

function swTemplate(version: string, precache: string[]): string {
  return `// Generated by the fort-pwa build plugin. Do not edit by hand.
const VERSION = ${JSON.stringify(version)};
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(VERSION).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter((k) => k !== VERSION).map((k) => caches.delete(k)));
      await self.clients.claim();
    })(),
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: try the network, fall back to the cached shell when offline.
  if (req.mode === "navigate") {
    event.respondWith(
      (async () => {
        try {
          return await fetch(req);
        } catch (e) {
          const cache = await caches.open(VERSION);
          return (await cache.match("/index.html")) || (await cache.match("/")) || Response.error();
        }
      })(),
    );
    return;
  }

  // Assets: cache-first with a background revalidate (they are content-hashed).
  // Match loosely (ignore query and Vary, fall back to the pathname) so a
  // crossorigin module request still resolves to the precached response offline.
  event.respondWith(
    (async () => {
      const cache = await caches.open(VERSION);
      const opts = { ignoreSearch: true, ignoreVary: true };
      const cached = (await cache.match(req, opts)) || (await cache.match(url.pathname, opts));
      if (cached) return cached;
      try {
        const res = await fetch(req);
        if (res && res.ok) cache.put(req, res.clone());
        return res;
      } catch (e) {
        return Response.error();
      }
    })(),
  );
});
`;
}

function fortPwa(): Plugin {
  return {
    name: "fort-pwa",
    apply: "build",
    generateBundle(_options, bundle) {
      // Precache the shell and hashed JS/CSS, but not sourcemaps (dead weight
      // offline) or the SW itself.
      const emitted = Object.keys(bundle)
        .filter((f) => !f.endsWith(".map") && f !== "sw.js")
        .map((f) => "/" + f);
      const precache = Array.from(new Set([...PUBLIC_SHELL, ...emitted]));
      const version = "fort-" + hashList(precache.slice().sort().join(","));
      this.emitFile({ type: "asset", fileName: "sw.js", source: swTemplate(version, precache) });
    },
  };
}

export default defineConfig({
  root: ".",
  plugins: [fortPwa()],
  build: {
    target: "es2022",
    outDir: "dist",
    sourcemap: true,
  },
  server: {
    port: 5173,
    strictPort: true,
  },
  preview: {
    port: 4173,
    strictPort: true,
  },
});
